Repository Alvarado007/segundo-miniproyecto-java-gui, pull requests merged in 2025-05, with the labels that each got.

#2 Ajustes imagenes
  bin/Imagenes/pokemones/Abra.png
  bin/Imagenes/pokemones/Alakazam.png
  bin/Imagenes/pokemones/Arcanine.png
  bin/Imagenes/pokemones/Blastoise.png
  bin/Imagenes/pokemones/Bulbasaur.png
  bin/Imagenes/pokemones/Celebi.png
  bin/Imagenes/pokemones/Charizard.png
  bin/Imagenes/pokemones/Charmander.png
  bin/Imagenes/pokemones/Delphox.png
  bin/Imagenes/pokemones/Eevee.png
  bin/Imagenes/pokemones/Gardevoir.png
  bin/Imagenes/pokemones/Gengar.png
  bin/Imagenes/pokemones/Greninja.png
  bin/Imagenes/pokemones/Gyarados.png
  bin/Imagenes/pokemones/Incineroar.png
  bin/Imagenes/pokemones/Jigglypuff.png
  bin/Imagenes/pokemones/Lucario.png
  bin/Imagenes/pokemones/Lugia.png
  bin/Imagenes/pokemones/Magikarp.png
  bin/Imagenes/pokemones/Meowth.png
  bin/Imagenes/pokemones/Mewtwo.png
  bin/Imagenes/pokemones/Pikachu.png
  bin/Imagenes/pokemones/Psyduck.png
  bin/Imagenes/pokemones/Raichu.png
  bin/Imagenes/pokemones/Rayquaza.png
  bin/Imagenes/pokemones/Snorlax.png
  bin/Imagenes/pokemones/Squirtle.png
  src/Clases/Entrenador.java
  src/Imagenes/pokemones/Abra.png
  src/Imagenes/pokemones/Alakazam.png
  src/Imagenes/pokemones/Arcanine.png
  src/Imagenes/pokemones/Blastoise.png
  src/Imagenes/pokemones/Bulbasaur.png
  src/Imagenes/pokemones/Celebi.png
  src/Imagenes/pokemones/Charizard.png
  src/Imagenes/pokemones/Charmander.png
  src/Imagenes/pokemones/Delphox.png
  src/Imagenes/pokemones/Eevee.png
  src/Imagenes/pokemones/Gardevoir.png
  src/Imagenes/pokemones/Gengar.png
  src/Imagenes/pokemones/Greninja.png
  src/Imagenes/pokemones/Gyarados.png
  src/Imagenes/pokemones/Incineroar.png
  src/Imagenes/pokemones/Jigglypuff.png
  src/Imagenes/pokemones/Lucario.png
  src/Imagenes/pokemones/Lugia.png
  src/Imagenes/pokemones/Magikarp.png
  src/Imagenes/pokemones/Meowth.png
  src/Imagenes/pokemones/Mewtwo.png
  src/Imagenes/pokemones/Pikachu.png
  src/Imagenes/pokemones/Psyduck.png
  src/Imagenes/pokemones/Raichu.png
  src/Imagenes/pokemones/Rayquaza.png
  src/Imagenes/pokemones/Snorlax.png
  src/Imagenes/pokemones/Squirtle.png
Labels: visualize

#3 Se crea la clase SeleccionPokemon, donde se muestran tanto los nombre…
  src/Vistas/BatallaPokemon.java
  src/Vistas/SeleccionPokemon.java
Labels: enhancement

#4 Batalla
  src/Clases/Entrenador.java
  src/Clases/Pokemon.java
  src/Clases/Visualizacion.java
  src/Vistas/BatallaPokemon.java
  src/Vistas/Entrenadores.java
  src/Vistas/InicioPokemon.java
  src/Vistas/SeleccionPokemon.java
Labels: visualize

#9 Cambios en el codigo para hacer pokemones random
  bin/Imagenes/Logos/Ash.jpeg
  bin/Imagenes/Logos/Giovanni.jpeg
  src/Clases/Ataque.java
  src/Clases/Entrenador.java
  src/Imagenes/Logos/Ash.jpeg
  src/Imagenes/Logos/Giovanni.jpeg
  src/Vistas/SeleccionPokemon.java
Labels: fixes

#12 Se agrega la estadística ataque al constructor de Pokemon para modifi…
  src/Clases/Entrenador.java
  src/Clases/Pokemon.java
Labels: enhancement

#14 cambio random
  src/Clases/Ataque.java
  src/Clases/Entrenador.java
Labels: fixes

#19 Ataques especiales
  src/Clases/Ataque.java
  src/Clases/Entrenador.java
  src/Clases/Pokemon.java
  src/Vistas/BatallaPokemon.java
  src/Vistas/InicioPokemon.java
  src/Vistas/SeleccionPokemon.java
Labels: fixes
